config/routes.rb
Rails.application.routes.draw do

  
  root to: 'pages#homepage'
  
  get 'about', to: 'pages#about'
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  validates :title, presence: true, length: {minimum: 3, maximum: 10}
  validates :description, presence: true, length: {minimum: 10, maximum:50}
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @article = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to article_path(@article)
      
    else
      render 'new'
    end
  end
  
  def update 
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show 
    @article = Article.find(params[:id])  
  end
  
  
  private

    def article_params
      params.require(:article).permit(:title, :description)
    end
    
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def homepage
  end
  
  def about
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<!DOCTYPE>
<html>
  <head>

  </head>
  <body>
    <h1>Edit existing article</h1>
    <% if @article.errors.any? %>
      <h2> The following errors prevented the article from getting created</h2>
      <ul>
        <% @article.erros.full-messages.each do |msg| %>
        <li><% msg %></li>
        <% end %>
      </ul>
    <% end %>
    <%= form_for @article do |f| %>
     <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p> 
    
    <p>
      <%= f.label :description %><br/>
      <%= f.text_field :description %>
    </p>
    
    <p>
      <%= f.submit %>
    </p>
    <% end %>
    
    <%= link_to "Go back to article list", articles_path %>
    
   
  </body>
</html>

app/views/articles/index.html.erb
<!DOCTYPE>
<html>
  <head>
  </head>
  <body>
    <h1>This is the list of Article</h1>
    <p>
    <%= link_to "Create new article", new_article_path %>
    </p>
    <table>
      <tr>
        <th>Title</th>
        <th>Description</th>
      </tr>
      
      
      <% @article.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to "Edit", edit_article_path(article) %></td>
        <td><%= link_to "Show", article_path(article) %></td>
      </tr>
      
      <% end %>
      
    </table>
  </body>
</html>

app/views/articles/new.html.erb
<!DOCTYPE>
<html>
  <head>
    <title>Article</title>
  </head>
  <body>
    <h1>Create an article</h1>
    
  <% if @article.errors.any? %>
  <h1>The following erros prevented the article from getting created</h1>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
    
    <%= form_for @article do |f| %>
      <p>
        <%= f.label :title %><br/>
        <%= f.text_field :title %>
      </p>
      <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
      </p>
      <p>
        <%= f.submit %>
      </p>
  
    
    
    <% end %>
    
    <%= link_to "Back to article listing", articles_path %>
    
  </body>
</html>

app/views/articles/show.html.erb
<!DOCTYPE>
<html>
  <head>
  
  </head>
  <body>
    <h1>Showing selected article</h1>
    <p>
      Title: <%= @article.title %>
    </p>
    <p>
      Description: <%= @article.description %>
    </p>
    <%= link_to "edit this article", edit_article_path(@article) %> |
    <%= link_to "Go back to article list", articles_path %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE>
<html>
  <head>
    <style>
      #c {text-align:center;}
    </style>
    <h1 id='c'>About</h1>
  </head>
  <body id='c'>
    <%= link_to 'Home Page', root_path %>
  </body>
</html>

app/views/pages/homepage.html.erb
<!DOCTYPE>
<html>
  <head>
    <style>
      #c {text-align:center;}
    </style>
    <h1 id="c">HomePage</h1>
  </head>
  <body id='c'>
    <%= link_to 'About Page', about_path %>
    <p>test app</p>
  </body>
</html>